import { Product } from './types'

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Sentinel Pro 4K',
    price: 2499,
    originalPrice: 2999,
    image: '/images/drone-sentinel-pro.png',
    category: 'Professional Drones',
    subcategory: 'Surveillance',
    rating: 4.8,
    reviews: 342,
    inStock: true,
    description: 'Advanced surveillance drone with 4K thermal imaging',
    specs: {
      'Flight Time': '45 minutes',
      'Max Speed': '75 km/h',
      'Range': '8 km',
      'Camera': '4K Thermal',
      'Wind Resistance': '50 km/h',
    },
    features: [
      'Thermal imaging technology',
      '45-minute flight time',
      'Obstacle avoidance system',
      'Waterproof design',
      'Military-grade encryption',
    ],
    images: ['/images/drone-sentinel-pro.png'],
  },
  {
    id: '2',
    name: 'Guardian X500',
    price: 1899,
    originalPrice: 2199,
    image: '/images/drone-guardian-x500.png',
    category: 'Professional Drones',
    subcategory: 'Mapping',
    rating: 4.7,
    reviews: 287,
    inStock: true,
    description: 'High-precision mapping drone for industrial applications',
    specs: {
      'Flight Time': '38 minutes',
      'Max Speed': '68 km/h',
      'Range': '7 km',
      'Camera': '48MP RGB',
      'Accuracy': '±2cm',
    },
    features: [
      '48MP RGB camera',
      'LiDAR integration',
      'Autonomous flight planning',
      '38-minute endurance',
      'IP67 waterproof rating',
    ],
    images: ['/images/drone-guardian-x500.png'],
  },
  {
    id: '3',
    name: 'Viper 3000 Elite',
    price: 1649,
    originalPrice: 1999,
    image: '/images/drone-viper-3000.png',
    category: 'Combat Drones',
    subcategory: 'Tactical',
    rating: 4.9,
    reviews: 512,
    inStock: true,
    description: 'Precision tactical drone for advanced operations',
    specs: {
      'Flight Time': '52 minutes',
      'Max Speed': '85 km/h',
      'Range': '10 km',
      'Payload': '5 kg',
      'Armament': 'Modular',
    },
    features: [
      'Advanced targeting system',
      'Modular payload system',
      '52-minute flight time',
      'Stealth design',
      'Multi-sensor fusion',
    ],
    images: ['/images/drone-viper-3000.png'],
  },
  {
    id: '4',
    name: 'Aurora Reconnaissance',
    price: 3299,
    originalPrice: 3999,
    image: '/images/drone-aurora.png',
    category: 'Military Grade',
    subcategory: 'ISR',
    rating: 4.9,
    reviews: 189,
    inStock: true,
    description: 'Intelligence, Surveillance & Reconnaissance drone',
    specs: {
      'Flight Time': '60 minutes',
      'Max Speed': '95 km/h',
      'Range': '15 km',
      'Camera': '8K ISR Suite',
      'Altitude': '5000m',
    },
    features: [
      '8K ISR camera suite',
      'Full spectrum sensing',
      '60-minute endurance',
      'Autonomous navigation',
      'Classified data encryption',
    ],
    images: ['/images/drone-aurora.png'],
  },
  {
    id: '5',
    name: 'Falcon Scout Lite',
    price: 799,
    originalPrice: 999,
    image: '/images/drone-falcon-lite.png',
    category: 'Consumer Drones',
    subcategory: 'Entry Level',
    rating: 4.6,
    reviews: 1203,
    inStock: true,
    description: 'Affordable entry-level drone for beginners',
    specs: {
      'Flight Time': '25 minutes',
      'Max Speed': '50 km/h',
      'Range': '3 km',
      'Camera': '2K FHD',
      'Weight': '250g',
    },
    features: [
      'Compact foldable design',
      '25-minute flight time',
      'Beginner-friendly controls',
      '2K camera',
      'AI tracking',
    ],
    images: ['/images/drone-falcon-lite.png'],
  },
  {
    id: '6',
    name: 'Phoenix Heavy Lift',
    price: 4499,
    image: '/images/drone-phoenix.png',
    category: 'Industrial',
    subcategory: 'Cargo',
    rating: 4.8,
    reviews: 145,
    inStock: true,
    description: 'Heavy-lift cargo drone for logistics operations',
    specs: {
      'Flight Time': '35 minutes',
      'Max Speed': '60 km/h',
      'Range': '6 km',
      'Payload': '25 kg',
      'Power': 'Hybrid electric',
    },
    features: [
      '25kg payload capacity',
      'Hybrid-electric propulsion',
      'Autonomous delivery',
      'Weather resistant',
      'GPS + RTK positioning',
    ],
    images: ['/images/drone-phoenix.png'],
  },
]

export const CATEGORIES = [
  { id: 'professional', name: 'Professional Drones', count: 8 },
  { id: 'military', name: 'Military Grade', count: 5 },
  { id: 'consumer', name: 'Consumer Drones', count: 12 },
  { id: 'industrial', name: 'Industrial', count: 4 },
  { id: 'combat', name: 'Combat Drones', count: 3 },
]

export const PRICE_RANGES = [
  { label: 'Under IND 500', min: 0, max: 500 },
  { label: 'IND 500 - 1,000', min: 500, max: 1000 },
  { label: 'IND 1,000 - 2,000', min: 1000, max: 2000 },
  { label: 'IND 2,000 - 3,000', min: 2000, max: 3000 },
  { label: 'Over IND 3,000', min: 3000, max: 999999 },
]

export const RATINGS = [
  { stars: 5, label: '5 Stars' },
  { stars: 4, label: '4 Stars & up' },
  { stars: 3, label: '3 Stars & up' },
]
